//! `vuo-shim` — the Qt-facing half of Vuo.
//!
//! Everything in this crate exists to make [`vuo_core`] visible to QML and
//! nothing else. There is no application logic here: no sync policy, no
//! parsing, no conflict resolution. If something in this crate starts making a
//! decision, it belongs in the core, where it can be tested without Qt.
//!
//! # `unsafe` lives here, and only here
//!
//! §9.5 puts `#![forbid(unsafe_code)]` in `vuo-core` and confines `unsafe` to
//! this crate, *"where `qmetaobject` requires it, and reviewed line by line"*.
//! In practice all of it is generated by the `QObject` derive and the `cpp!`
//! macro; this crate writes no `unsafe` block of its own.
//!
//! # Registration, not application ownership
//!
//! [`register_qml_types`] registers types and returns. It deliberately does not
//! create a `QmlEngine`: `QmlEngine::new()` constructs a **QtWidgets**
//! `QApplication`, which is not what a Silica app wants — Sailfish needs
//! `SailfishApp::application()` and `SailfishApp::createView()` for correct
//! Wayland, booster and theme setup. `qml_register_type` needs no engine at
//! all, so the Sailfish binary owns the application and calls in here to
//! register.
//!
//! # Qt 5.6 constraints that shaped this code
//!
//! `qmetaobject`'s build script emits `qt_5_7` through `qt_5_15` cfgs and
//! nothing for 5.6, so on the Sailfish target **`qml_register_enum`,
//! `qml_register_module` and `qml_register_singleton_instance` do not exist**.
//! Enums therefore cross into QML as plain integers (see
//! [`models::Scope::from_qml`]) and strings, rather than as registered types.

// QML-visible members are camelCase on purpose.
//
// `qmetaobject` emits property, method and signal names to the meta-object
// VERBATIM -- there is no snake_case-to-camelCase conversion -- so whatever is
// written here is exactly what QML must type. Qt's convention is camelCase, and
// this struct's public surface *is* a Qt API, so it follows Qt's convention
// rather than Rust's. The alternative is QML reading `model.set_read(...)` and
// a signal handler spelled `onConnection_tested`.
#![allow(non_snake_case)]
// The panic denials exist because unwinding out of Rust into Qt's C++ frames
// is undefined behaviour (§9.5). Test code has neither foreign input nor a Qt
// frame above it, and a panicking assertion is the entire point of a test.
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing
    )
)]

pub mod article;
pub mod context;
pub mod models;
pub mod settings;
pub mod worker;

use cstr::cstr;
use qmetaobject::*;

/// Register Vuo's types with the QML engine.
///
/// Call once, before loading QML. Safe to call from a Sailfish `main` that owns
/// the `QApplication`, because this touches no engine.
pub fn register_qml_types() {
    qml_register_type::<models::EntryModel>(cstr!("Vuo"), 1, 0, cstr!("EntryModel"));
    qml_register_type::<models::FeedModel>(cstr!("Vuo"), 1, 0, cstr!("FeedModel"));
    qml_register_type::<article::ArticleModel>(cstr!("Vuo"), 1, 0, cstr!("ArticleModel"));
    qml_register_type::<settings::Settings>(cstr!("Vuo"), 1, 0, cstr!("Settings"));
}

/// C ABI entry point, for a Sailfish binary whose `main` is C++.
///
/// # Safety
///
/// Must be called from the Qt thread, once, before any QML is loaded.
#[no_mangle]
pub extern "C" fn vuo_register_qml_types() {
    register_qml_types();
}

#[cfg(test)]
mod tests {
    use super::*;
    use vuo_core::content::{MediaPolicy, TransformContext};

    /// The offscreen Qt smoke test §8.1 asks for.
    ///
    /// *"Exercises the shim under `QT_QPA_PLATFORM=offscreen` on a headless
    /// runner. Catches model-registration and threading mistakes without a
    /// device."*
    ///
    /// What it covers is that registering does not abort and is idempotent --
    /// a malformed meta-object aborts the process here rather than failing a
    /// return value, and a plugin can be loaded more than once.
    ///
    /// What it CANNOT cover: whether Qt accepted each registration.
    /// `qml_register_type` in qmetaobject 0.2.10 returns `()`, discarding the
    /// type id that would be -1 on rejection, so there is nothing to assert.
    /// A registration that silently did nothing is caught one level up, by
    /// tests/qml_loads.rs: the QML then names a type the engine does not know
    /// and every page fails to compile. Registering under the wrong name is
    /// caught the same way.
    #[test]
    fn types_register_without_a_display() {
        register_qml_types();
        // Registering twice must also be harmless: a plugin can be loaded more
        // than once, and Qt tolerates re-registration.
        register_qml_types();

        // And each registered type is a well-formed QObject that can actually
        // be default-constructed, which is what QML does with `EntryModel {}`.
        assert_eq!(models::EntryModel::default().row_count(), 0);
        assert_eq!(models::FeedModel::default().row_count(), 0);
        assert_eq!(article::ArticleModel::default().row_count(), 0);
        assert_eq!(settings::Settings::default().sync_interval_minutes(), None);
    }

    #[test]
    fn an_article_model_transforms_and_exposes_blocks() {
        let mut model = article::ArticleModel::default();
        let instance = url::Url::parse("https://miniflux.example/").unwrap();
        let ctx = TransformContext {
            media: MediaPolicy::ProxyThroughInstance {
                instance: instance.clone(),
                extra_trusted: Vec::new(),
                fallback: vuo_core::content::UnproxiedMedia::Strict,
            },
            ..TransformContext::new(instance)
        };

        model.set_html(
            "<h2>Title</h2><p>Body with <b>bold</b> and a <a href=\"javascript:alert(1)\">bad link</a>.</p>",
            &ctx,
        );

        assert_eq!(model.rows().len(), 2);
        let heading = model.rows().first().expect("heading");
        assert_eq!(heading.kind, "heading");
        assert_eq!(heading.level, 2);

        let body = model.rows().get(1).expect("paragraph");
        assert!(
            body.text.contains("<b>bold</b>"),
            "styling should survive: {}",
            body.text
        );
        assert!(
            !body.text.contains("javascript:"),
            "a dangerous href must never reach QML: {}",
            body.text
        );
        assert!(
            body.text.contains("bad link"),
            "but its text is still readable"
        );
    }

    #[test]
    fn hostile_markup_reaches_qml_escaped() {
        let mut model = article::ArticleModel::default();
        let instance = url::Url::parse("https://miniflux.example/").unwrap();
        let ctx = TransformContext::new(instance);
        model.set_html("<p>&lt;img src=x onerror=alert(1)&gt;</p>", &ctx);

        let row = model.rows().first().expect("a paragraph");
        assert!(
            !row.text.contains("<img"),
            "unescaped markup reached the UI: {}",
            row.text
        );
        assert!(
            row.text.contains("&lt;img"),
            "the text itself should still be shown"
        );
    }

    #[test]
    fn un_proxied_images_are_flagged_rather_than_silently_dropped() {
        let mut model = article::ArticleModel::default();
        let instance = url::Url::parse("https://miniflux.example/").unwrap();
        let ctx = TransformContext {
            base_url: url::Url::parse("https://blog.example/post/").ok(),
            ..TransformContext::new(instance)
        };
        model.set_html(
            "<p><img src=\"https://tracker.example/p.gif\" alt=\"x\"></p>",
            &ctx,
        );

        let image = model
            .rows()
            .iter()
            .find(|r| r.kind == "image")
            .expect("an image row");
        assert!(
            image.needs_consent,
            "the UI must ask before leaking the device IP"
        );
        assert_eq!(model.blockedImages, 1);
    }

    #[test]
    fn truncation_is_reported_to_the_ui() {
        let mut model = article::ArticleModel::default();
        let instance = url::Url::parse("https://miniflux.example/").unwrap();
        let mut ctx = TransformContext::new(instance);
        ctx.limits.max_blocks = 5;
        model.set_html(&"<p>x</p>".repeat(50), &ctx);
        assert!(
            model.truncated,
            "a silent truncation reads as 'this is the whole article'"
        );
    }

    #[test]
    fn a_model_with_no_database_does_not_panic() {
        // QML instantiates these before Rust attaches a mirror.
        let mut model = models::EntryModel::default();
        model.reload();
        assert_eq!(model.rows().len(), 0);
    }
}
